version: "3.2"

services:
  api:
    build: api
    container_name: kiba_api
    cap_add:
      - CAP_SYS_ADMIN
    restart: always
    ports:
      - 2000:2000
    volumes:
      - ./data/kiba:/kiba
    environment:
      - KIBA_REPO_URL=http://repo:8000/index
    tmpfs:
      - /kiba/jobs:exec

  repo: # Local testing of packages
    build: repo
    container_name: kiba_repo
    command: ["--no-build"] # Don't build anything
    volumes:
      - .:/kiba
