version: "3.2"

services:
  api:
    image: ghcr.io/parzuko/kiba
    container_name: kiba_api
    restart: always
    ports:
      - 2000:2000
    volumes:
      - ./data/kiba:/kiba
    tmpfs:
      - /kiba/jobs:exec
      - /tmp:exec
